### ISSUE TITLE
Fix ur.py syntax error

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#71]
When attempting to `import` the [ur.py](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur.py) module with `ipython` the follow syntax error occured:

```ipython3
[ins] In [1]: import ur
Traceback (most recent call last):

  File ~/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3378 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In [1], line 1
    import ur

  File ~/Projects/oneapi-src/unified-runtime/include/ur.py:1815
    _urDeviceSelectBinary_t = WINFUNCTYPE( ur_result_t, ur_device_handle_t, POINTER(c_ubyte*), c_ulong, POINTER(c_ulong) )
                                                                                            ^
SyntaxError: invalid syntax
```

Looks like argument which are pointer to pointer types are not being handled correctly. There may be other syntax issues hidden by this error also.

Fix the syntax errors, and make sure the `ur.py` module can, at the very least, be imported. Ideally this would also introduce CI testing to avoid regressions happening in future. More extensive testing, actually using the library, will probably have to wait though.

**Comment by FranklandJack** [comment]
Managed to fix the first issue but I'm now seeing a type error on import:
```
>>> import ur
Traceback (most recent call last):
  File "/usr/lib/python3.8/ctypes/__init__.py", line 99, in CFUNCTYPE
    return _c_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ur.ur_result_t'>, (<class 'ur.ur_context_handle_t'>, <function ur_context_extended_deleter_t at 0x7f55e5623dc0>, <class 'ctypes.c_void_p'>), 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/unified-runtime/include/ur.py", line 1029, in <module>
    _urContextSetExtendedDeleter_t = CFUNCTYPE( ur_result_t, ur_context_handle_t, ur_context_extended_deleter_t, c_void_p )
  File "/usr/lib/python3.8/ctypes/__init__.py", line 101, in CFUNCTYPE
    class CFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ has no from_param method
```
